### ISSUE TITLE
Update to latest version of the Appboy SDK

### ISSUE THREAD

**Issue by dazmuda** [mparticle-integrations/mparticle-apple-integration-appboy#12]
v3.1.1 just came out, fixes an issue with setting custom current attributes.

**Comment by dazmuda** [comment]
@peterjenkins Would be good to get this in soon! We're probably not the only ones affected by this issue, it's rather gnarly: https://github.com/Appboy/appboy-ios-sdk/blob/master/CHANGELOG.md

**Comment by samdozor** [comment]
@dazmuda you can pull in 3.1.1 with the current versoin of the podspec. Are you using Carthage?
