### ISSUE TITLE
Setting ABKInAppMessageControllerDelegate when starting Appboy to avoid race condition

### ISSUE THREAD

**Issue by saniul** [mparticle-integrations/mparticle-apple-integration-appboy#3]
Note the first point in the [2.25.0 release notes](https://github.com/Appboy/appboy-ios-sdk/releases/tag/2.25.0), especially:
> This is the recommended way to set the ABKInAppMessageControllerDelegate and circumvents a potential race condition where in-app messages can be shown before the delegate has been set.

How can we conform to this recommendation when Appboy is started by mParticle?

**Comment by samdozor** [comment]
hey @saniul we can definitely look at exposing an API for this. Seems like the race condition would happen when in-app messages are shown immediately on startup - are you seeing that behavior?

**Comment by saniul** [comment]
We haven't seen that behaviour yet, but looks like the risk is there, considering they mentioned it in their release notes (cc @wenzhi). I can't say for sure, since their SDK is not open source.

**Comment by Wenzhi** [comment]
Hey @saniul and @samdozor, 

There was a rare edge case in which in-app messages showed before the delegate had been set when the app launched from suspended mode, hence the change. 

@samdozor, is it feasible to expose that API so users have access to the update? Thanks for being so on top of our changes :)

Thanks,
Wenzhi

**Comment by samdozor** [comment]
We've released an API for this: https://github.com/mparticle-integrations/mparticle-apple-integration-appboy/commit/e710b1a11a4a2589f63d8d9d28deaec69c0b2bbb
