### ISSUE TITLE
Inconsistent Appboy integration using CocoaPods

### ISSUE THREAD

**Issue by SiarheiBarysenka** [mparticle-integrations/mparticle-apple-integration-appboy#8]
Hi there!

I encountered an issue with inconsistent mParticle/Appboy integration using CocoaPods. Please find the test project here: 
[MParticleWithAppboyIntegration_WithoutInstalledPods.zip](https://github.com/mparticle-integrations/mparticle-apple-integration-appboy/files/1144710/MParticleWithAppboyIntegration_WithoutInstalledPods.zip)

I use CocoaPods version 1.2.1 on my machine, here is the Podfile for the test project 

```
platform :ios, '9.0'
use_frameworks!

pre_install do |pre_i|
    def pre_i.verify_no_static_framework_transitive_dependencies; end
end

target 'MParticleWithAppboyIntegration' do
    pod 'mParticle-Appboy'
    pod 'mParticle-Kochava'
end
```
The versions from the Podfile.lock are the following:
```
- mParticle-Appboy (6.14.1):
  - Appboy-iOS-SDK (= 2.29.0)
  - mParticle-Apple-SDK/mParticle (~> 6.14.0)
```
When I run the app, the following message regarding ambiguous Appboy implementation can be seen in the console:

```
objc[29395]: Class Appboy is implemented in both /Users/siarheibarysenka/Library/Developer/CoreSimulator/Devices/36A01E77-E810-4D8E-A1E8-
2C6008EEF170/data/Containers/Bundle/Application/3194ACE0-D199-48EE-9C3D-
A44F7F8E9313/MParticleWithAppboyIntegration.app/Frameworks/mParticle_Appboy.framework/
mParticle_Appboy (0x10e7dd3a8) and /Users/siarheibarysenka/Library/Developer/CoreSimulator/Devices/36A01E77-E810-4D8E-A1E8-
2C6008EEF170/data/Containers/Bundle/Application/3194ACE0-D199-48EE-9C3D-
A44F7F8E9313/MParticleWithAppboyIntegration.app/Frameworks/Appboy_iOS_SDK.framework/
Appboy_iOS_SDK (0x10bf61c28). One of the two will be used. Which one is undefined.
```

In this test app, I'd like to get access to `appboy.inAppMessageController.delegate` in order to control in-app messages display cycle. I want to delay a message in some particular cases (it appears to be the in-app message is not responsive for user interaction when it's displayed right on the start of the app). However, I can not access the initialized `Appboy` instance. The following code

```
import UIKit
import mParticle_Appboy
import Appboy_iOS_SDK

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    var window: UIWindow?

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        MParticle.sharedInstance().logLevel = .none
        MParticle.sharedInstance().start(withKey: "put_key_here", secret: "put_secret_here")
        
        MParticle.sharedInstance().kitInstance(MPKitAppboy.kitCode()) { instance in
            guard let unknownAppboy = instance else {
                print("Returned instance is nil")
                return
            }
            
            if let appboy = unknownAppboy as? Appboy {
                print("Appboy can be succesfully accessed: \(appboy)")
            } else {
                print("Appboy can not be succesfully accessed")
                print("Returned type: \(type(of: unknownAppboy))")
                print("Known Appboy type: \(Appboy.self)")
                print("Instance of unknown Appboy type: \(unknownAppboy)")
            }
        }
        
        return true
    }
}
```
 when executed with proper key/secret/bundleID gives the following output:
```
Appboy can not be succesfully accessed
Returned type: Appboy
Known Appboy type: Appboy
Instance of unknown Appboy type: <Appboy: 0x6080000f3d00>
```

It looks like a direct aftermath of the issue with duplicate Appboy implementation mentioned above.

Any help to conventionally resolve these issues is much appreciated!

**Comment by samdozor** [comment]
Hi @SiarheiBarysenka thank for reporting this and the in-depth issue write-up. This is unfortunately the result of Appboy being a static framework, rather than dynamic. You can read a lengthy discussion here:  https://github.com/CocoaPods/CocoaPods/issues/2926

That means their library is currently incompatible with !use_frameworks, when it's been wrapped in a dynamic library such as this kit. If you need to consistently access the reference from user-level code, you'll need to incorporate it manually:
1. Add the `Appboy-iOS-SDK` pod directly to your Podfile
2. Remove the `mParticle-Appboy` pod and manually drag the m/h of the Appboy kit into your project: https://github.com/mparticle-integrations/mparticle-apple-integration-appboy/tree/master/mParticle-Appboy

We realize this is not an ideal solution while we wait for Appboy to support a dynamic framework.

**Comment by SiarheiBarysenka** [comment]
@samdozor Thank you so much for the prompt response! It really helps.

By the way, this setup "automagically" fixed my original issue regarding not responsive in-app messages delivered on the start of the app. Would you mind adding these installation guides explicitly in README file? I suppose it may save a lot of time for the people that experience the same issue too.

**Comment by samdozor** [comment]
This is being added to our primary documentation site. Thanks for the report! Closing.
