### ISSUE TITLE
Gender always male?

### ISSUE THREAD

**Issue by getaaron** [mparticle-integrations/mparticle-apple-integration-appboy#9]
Is the code on line 456:

https://github.com/mparticle-integrations/mparticle-apple-integration-appboy/blob/5a4b0c93969a1f6059371a13eaa6ca88852230c3/mParticle-Appboy/MPKitAppboy.m#L455-L457

equivalent to:

```objc
appboyInstance.user.gender = ABKUserGenderMale;
```

since `mParticleGenderMale` is `@"M"` and will always evaluate as true?

```objc
//  from MPEnums.m

NSString *const mParticleGenderMale = @"M";
```

**Comment by samdozor** [comment]
Hey @getaaron - yep this looks like a nasty 🐛  - we'll get it fixed.

**Comment by samdozor** [comment]
This will be release today as a part of 6.15.0. Thanks for reporting! Please report all future issues on the primary SDK repo: https://github.com/mParticle/mparticle-apple-sdk
